### ISSUE TITLE
MySQL database

### ISSUE THREAD

**Issue by geoffdgeorge** [geoffdgeorge/Patellr#3]
- [x] User database with the following columns: user_id, username, password
- [x] Progress database with the following columns: entry_id, user_id (as foreign key), pain_top, pain_bottom, pain_inside, pain_outside, pain_level, strength_level

**Comment by gjdivittorio** [comment]
**Page 1**
- [ ] user authentication (using columns referenced)
- [ ] create an account (for new user)

**Page 2**
- [ ] survey (answers would be added to database table)

Questions in the survey (database):
- [ ] pain level (mentioned above)
- [ ] duration of pain
- [ ] movement or exercise time

### Suggestion: For MVP, questions can require simple numeric inputs
